### ISSUE TITLE
value of type 'Data' has no member 'bytes'

### ISSUE THREAD

**Issue by ai0a** [apple/swift-configuration#139]
When trying to build on MacOS 15.7.3 with swift 6.2.3, after cloning this repository, I get the following errors, complaining about FileProvider.swift trying to access a `bytes` member of `Data`:
```
/Users/user/swift-configuration/Sources/Configuration/Providers/Files/FileProvider.swift:187:36: error: value of type 'Data' has no member 'bytes'
185 |         if let fileContents {
186 |             self._snapshot = try snapshotType.init(
187 |                 data: fileContents.bytes,
    |                                    `- error: value of type 'Data' has no member 'bytes'
188 |                 providerName: providerName,
189 |                 parsingOptions: parsingOptions
/Users/user/swift-configuration/Sources/Configuration/Providers/Files/FileProvider.swift:187:36: error: value of type 'Data' has no member 'bytes'
185 |         if let fileContents {
186 |             self._snapshot = try snapshotType.init(
187 |                 data: fileContents.bytes,
    |                                    `- error: value of type 'Data' has no member 'bytes'
188 |                 providerName: providerName,
189 |                 parsingOptions: parsingOptions
/Users/user/swift-configuration/Sources/Configuration/Providers/Files/FileProvider.swift:187:36: error: value of type 'Data' has no member 'bytes'
185 |         if let fileContents {
186 |             self._snapshot = try snapshotType.init(
187 |                 data: fileContents.bytes,
    |                                    `- error: value of type 'Data' has no member 'bytes'
188 |                 providerName: providerName,
189 |                 parsingOptions: parsingOptions
/Users/user/swift-configuration/Sources/Configuration/Providers/Files/FileProvider.swift:187:36: error: value of type 'Data' has no member 'bytes'
185 |         if let fileContents {
186 |             self._snapshot = try snapshotType.init(
187 |                 data: fileContents.bytes,
    |                                    `- error: value of type 'Data' has no member 'bytes'
188 |                 providerName: providerName,
189 |                 parsingOptions: parsingOptions
/Users/user/swift-configuration/Sources/Configuration/Providers/Files/FileProvider.swift:187:36: error: value of type 'Data' has no member 'bytes'
185 |         if let fileContents {
186 |             self._snapshot = try snapshotType.init(
187 |                 data: fileContents.bytes,
    |                                    `- error: value of type 'Data' has no member 'bytes'
188 |                 providerName: providerName,
189 |                 parsingOptions: parsingOptions
/Users/user/swift-configuration/Sources/Configuration/Providers/Files/FileProvider.swift:187:36: error: value of type 'Data' has no member 'bytes'
185 |         if let fileContents {
186 |             self._snapshot = try snapshotType.init(
187 |                 data: fileContents.bytes,
    |                                    `- error: value of type 'Data' has no member 'bytes'
188 |                 providerName: providerName,
189 |                 parsingOptions: parsingOptions
```

I also get the same error when trying to use it in my own project, depending on it with
```swift
.package(
            url: "https://github.com/apple/swift-configuration",
            from: "1.0.0",
            traits: [.defaults, "CommandLineArguments", "YAML"]
        ),
```

**Comment by czechboy0** [comment]
Hi @ai0a,

which Xcode version are you running? Can you confirm your `swift -version`, please?

**Comment by joe-bro-1** [comment]
Hi @czechboy0,

I came across the same problem, after looking around a bit I found that the `swiftc` command being made targets `arm64-apple-macosx10.13` which as per [`Foundation.Data.bytes: RawSpan` @ Apple Developer](https://developer.apple.com/documentation/foundation/data/bytes) requires at least `macOS 10.14.4`

This looks to me to be an issue with the build chain, rather than `swift-configuration` [see below], although I am not quite sure what's triggering it.

Even adding a platform requirement to the `swift-configuration` package didn't solve the issue, it made it use the specified minimum (i tried both `10_14` & `10_15`), which **did** make the `swiftc` command use `arm64-apple-macosx10.14` & `arm64-apple-macosx10.15` respectively, but the build still fails with the same error.

<details>
    <summary>
        swiftc command (from swift build --verbose)
    </summary>

> [TOOLCHAIN_DIR]/usr/bin/swiftc -module-name Configuration -emit-dependencies -emit-module -emit-module-path [PROJECT_DIR]/.build/arm64-apple-macosx/debug/Modules/Configuration.swiftmodule -output-file-map [PROJECT_DIR]/.build/arm64-apple-macosx/debug/Configuration.build/output-file-map.json -parse-as-library -incremental -c @[PROJECT_DIR]/.build/arm64-apple-macosx/debug/Configuration.build/sources -I [PROJECT_DIR]/.build/arm64-apple-macosx/debug/Modules -target **arm64-apple-macosx10.13** -v -incremental -enable-batch-mode -serialize-diagnostics -index-store-path [PROJECT_DIR]/.build/arm64-apple-macosx/debug/index/store -Onone -enable-testing -j12 -DSWIFT_PACKAGE -DDEBUG -DSWIFT_MODULE_RESOURCE_BUNDLE_UNAVAILABLE -Xcc -fmodule-map-file=[PROJECT_DIR]/.build/checkouts/swift-system/Sources/CSystem/include/module.modulemap -Xcc -I -Xcc [PROJECT_DIR]/.build/checkouts/swift-system/Sources/CSystem/include -module-cache-path [PROJECT_DIR]/.build/arm64-apple-macosx/debug/ModuleCache -parseable-output -parse-as-library -emit-objc-header -emit-objc-header-path [PROJECT_DIR]/.build/arm64-apple-macosx/debug/Configuration.build/include/Configuration-Swift.h -color-diagnostics -swift-version 6 -DJSON -enable-upcoming-feature ExistentialAny -enable-upcoming-feature MemberImportVisibility -enable-upcoming-feature InternalImportsByDefault -enable-upcoming-feature NonisolatedNonsendingByDefault -enable-experimental-feature 'AvailabilityMacro=Configuration 1.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0' -I [TOOLCHAIN_DIR]/usr/lib/swift/macosx/testing -L [TOOLCHAIN_DIR]/usr/lib/swift/macosx/testing -plugin-path [TOOLCHAIN_DIR]/usr/lib/swift/host/plugins/testing -sdk /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -g -Xcc -isysroot -Xcc /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -Xcc -fPIC -Xcc -g -suppress-warnings -user-module-version 1.0.0 -package-name swift_configuration

a *similar* looking swiftc command came from each of the other toolchains and platform requirement options.
</details>

I tried with 3 Toolchains I had at hand, all failed in SPM, but succeeded in Xcode (configured via `Xcode > Toolchains`), this leads me to believe that its a particular frontend tool of swift not used in `xcode build` even when Xcode uses one of the Swift Open Source Toolchains

<details>
    <summary>
        Toolchains I tried
    </summary>

all of 

> main-snapshot-2026-01-06
> main-snapshot-2025-12-19
> main-snapshot-2025-08-27

which are

> $ swift --version
Apple Swift version 6.3-dev (LLVM 6f3e8e0c64f2c01, Swift 12e619fbba7fb85)
Target: arm64-apple-macosx26.0
Build config: +assertions

> $ swift --version                     
Apple Swift version 6.3-dev (LLVM f6e8f31819e2e67, Swift cecebdd863d2f71)
Target: arm64-apple-macosx26.0
Build config: +assertions

> $ swift --version                     
Apple Swift version 6.2-dev (LLVM fa1f889407fc8ca, Swift 687e09da65c8813)
Target: arm64-apple-macosx26.0
Build config: +assertions

respectively
</details>

**Comment by czechboy0** [comment]
Xcode 16.4 won't work, since Swift Configuration requires Swift 6.2, which was released in Xcode 26. So I suspect there's an Xcode + Swift toolchain mismatch, and you're using a Swift 6.2+ toolchain with an old, incompatible Xcode.

Updating your Xcode to 26+ should fix this.
